#------------------------------------------------------------------------------
# Copyright (C) 2009 Richard Lincoln
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation; version 2 dated June, 1991.
#
# This software is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANDABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
#------------------------------------------------------------------------------

""" Defines a map of class names to their module.
"""

dynamics_pkg_map = {
    "Element": "dynamics.element",
    "Model": "dynamics.model",
    "RotatingMachine": "dynamics.dynamics.rotating_machine",
    "MetaBlockConOutput": "dynamics.dynamics.meta_block_con_output",
    "AttributeBlockParameter": "dynamics.dynamics.attribute_block_parameter",
    "MetaBlock": "dynamics.dynamics.meta_block",
    "BlockParameter": "dynamics.dynamics.block_parameter",
    "MetaBlockReference": "dynamics.dynamics.meta_block_reference",
    "ExcitationSystemLimiter": "dynamics.dynamics.excitation_system_limiter",
    "MetaBlockConnectivity": "dynamics.dynamics.meta_block_connectivity",
    "ProtectiveDevice": "dynamics.dynamics.protective_device",
    "MetaBlockInput": "dynamics.dynamics.meta_block_input",
    "SourceModels": "dynamics.dynamics.source_models",
    "MetaBlockOutputReference": "dynamics.dynamics.meta_block_output_reference",
    "MetaBlockOutput": "dynamics.dynamics.meta_block_output",
    "MetaBlockParameter": "dynamics.dynamics.meta_block_parameter",
    "BlockConnection": "dynamics.dynamics.block_connection",
    "MetaBlockConInput": "dynamics.dynamics.meta_block_con_input",
    "StaticVarDevice": "dynamics.dynamics.static_var_device",
    "MetaBlockConnection": "dynamics.dynamics.meta_block_connection",
    "BlockConnectivity": "dynamics.dynamics.block_connectivity",
    "MetaBlockConSignal": "dynamics.dynamics.meta_block_con_signal",
    "Block": "dynamics.dynamics.block",
    "MetaBlockStateReference": "dynamics.dynamics.meta_block_state_reference",
    "AsynchronousMachine": "dynamics.dynamics.asynchronous_machine",
    "TieToMeasurement": "dynamics.dynamics.tie_to_measurement",
    "MetaBlockSignal": "dynamics.dynamics.meta_block_signal",
    "MetaBlockInputReference": "dynamics.dynamics.meta_block_input_reference",
    "MetaBlockParameterReference": "dynamics.dynamics.meta_block_parameter_reference",
    "MetaBlockConnectable": "dynamics.dynamics.meta_block_connectable",
    "MetaBlockState": "dynamics.dynamics.meta_block_state",
    "LoadStaticSystem": "dynamics.dynamics.loads.load_static_system",
    "LoadStaticOwner": "dynamics.dynamics.loads.load_static_owner",
    "LoadStatic": "dynamics.dynamics.loads.load_static",
    "AggregateLoad": "dynamics.dynamics.loads.aggregate_load",
    "LoadMotor": "dynamics.dynamics.loads.load_motor",
    "LoadStaticBus": "dynamics.dynamics.loads.load_static_bus",
    "LoadStaticZone": "dynamics.dynamics.loads.load_static_zone",
    "LoadStaticArea": "dynamics.dynamics.loads.load_static_area",
    "ExcBAS": "dynamics.dynamics.excitation_systems.exc_bas",
    "ExcDC2A": "dynamics.dynamics.excitation_systems.exc_dc2_a",
    "ExcSEXS": "dynamics.dynamics.excitation_systems.exc_sexs",
    "ExcELIN2": "dynamics.dynamics.excitation_systems.exc_elin2",
    "ExcAC4A": "dynamics.dynamics.excitation_systems.exc_ac4_a",
    "ExcSK": "dynamics.dynamics.excitation_systems.exc_sk",
    "ExcAC2A": "dynamics.dynamics.excitation_systems.exc_ac2_a",
    "ExcELIN1": "dynamics.dynamics.excitation_systems.exc_elin1",
    "ExcST6B": "dynamics.dynamics.excitation_systems.exc_st6_b",
    "ExcST4B": "dynamics.dynamics.excitation_systems.exc_st4_b",
    "ExcWT3E": "dynamics.dynamics.excitation_systems.exc_wt3_e",
    "ExcPIC": "dynamics.dynamics.excitation_systems.exc_pic",
    "ExcSK2": "dynamics.dynamics.excitation_systems.exc_sk2",
    "ExcST2A": "dynamics.dynamics.excitation_systems.exc_st2_a",
    "ExcHU": "dynamics.dynamics.excitation_systems.exc_hu",
    "ExcREXS": "dynamics.dynamics.excitation_systems.exc_rexs",
    "ExcST7B": "dynamics.dynamics.excitation_systems.exc_st7_b",
    "ExcAC1A": "dynamics.dynamics.excitation_systems.exc_ac1_a",
    "ExcDC4B": "dynamics.dynamics.excitation_systems.exc_dc4_b",
    "ExcDC1A": "dynamics.dynamics.excitation_systems.exc_dc1_a",
    "ExcAC3A": "dynamics.dynamics.excitation_systems.exc_ac3_a",
    "ExcAC6A": "dynamics.dynamics.excitation_systems.exc_ac6_a",
    "ExcAC5A": "dynamics.dynamics.excitation_systems.exc_ac5_a",
    "ExcST5B": "dynamics.dynamics.excitation_systems.exc_st5_b",
    "ExcSCRX": "dynamics.dynamics.excitation_systems.exc_scrx",
    "ExcAC8B": "dynamics.dynamics.excitation_systems.exc_ac8_b",
    "ExcWT2E": "dynamics.dynamics.excitation_systems.exc_wt2_e",
    "ExcAC7B": "dynamics.dynamics.excitation_systems.exc_ac7_b",
    "ExcWT4E": "dynamics.dynamics.excitation_systems.exc_wt4_e",
    "ExcST1A": "dynamics.dynamics.excitation_systems.exc_st1_a",
    "ExcBBC": "dynamics.dynamics.excitation_systems.exc_bbc",
    "ExcitationSystem": "dynamics.dynamics.excitation_systems.excitation_system",
    "ExcDC3A": "dynamics.dynamics.excitation_systems.exc_dc3_a",
    "ExcST3A": "dynamics.dynamics.excitation_systems.exc_st3_a",
    "ExcCZ": "dynamics.dynamics.excitation_systems.exc_cz",
    "GovHydro3": "dynamics.dynamics.turbine_governors.gov_hydro3",
    "GovHydro2": "dynamics.dynamics.turbine_governors.gov_hydro2",
    "GovGAST": "dynamics.dynamics.turbine_governors.gov_gast",
    "GovWT1T": "dynamics.dynamics.turbine_governors.gov_wt1_t",
    "TurbineGovernor": "dynamics.dynamics.turbine_governors.turbine_governor",
    "GovWT2P": "dynamics.dynamics.turbine_governors.gov_wt2_p",
    "GovHydroDD": "dynamics.dynamics.turbine_governors.gov_hydro_dd",
    "GovHydroWEH": "dynamics.dynamics.turbine_governors.gov_hydro_weh",
    "GovWT3T": "dynamics.dynamics.turbine_governors.gov_wt3_t",
    "GovHydroPID": "dynamics.dynamics.turbine_governors.gov_hydro_pid",
    "GovHydro4": "dynamics.dynamics.turbine_governors.gov_hydro4",
    "GovDUM": "dynamics.dynamics.turbine_governors.gov_dum",
    "GovHydroWPID": "dynamics.dynamics.turbine_governors.gov_hydro_wpid",
    "GovWT4P": "dynamics.dynamics.turbine_governors.gov_wt4_p",
    "TLCFB1": "dynamics.dynamics.turbine_governors.tlcfb1",
    "GovGASM": "dynamics.dynamics.turbine_governors.gov_gasm",
    "GovHydroR": "dynamics.dynamics.turbine_governors.gov_hydro_r",
    "GovSteamFV2": "dynamics.dynamics.turbine_governors.gov_steam_fv2",
    "GovRAV": "dynamics.dynamics.turbine_governors.gov_rav",
    "GovCT2": "dynamics.dynamics.turbine_governors.gov_ct2",
    "GovSteam1": "dynamics.dynamics.turbine_governors.gov_steam1",
    "GovSteamCC": "dynamics.dynamics.turbine_governors.gov_steam_cc",
    "GovSteamSGO": "dynamics.dynamics.turbine_governors.gov_steam_sgo",
    "GovSteamFV3": "dynamics.dynamics.turbine_governors.gov_steam_fv3",
    "GovWT3P": "dynamics.dynamics.turbine_governors.gov_wt3_p",
    "GovWT1P": "dynamics.dynamics.turbine_governors.gov_wt1_p",
    "GovSteam0": "dynamics.dynamics.turbine_governors.gov_steam0",
    "GovCT1": "dynamics.dynamics.turbine_governors.gov_ct1",
    "GovWT2T": "dynamics.dynamics.turbine_governors.gov_wt2_t",
    "GovHydro1": "dynamics.dynamics.turbine_governors.gov_hydro1",
    "GovHydroPID2": "dynamics.dynamics.turbine_governors.gov_hydro_pid2",
    "GovWT4T": "dynamics.dynamics.turbine_governors.gov_wt4_t",
    "GovSteamEU": "dynamics.dynamics.turbine_governors.gov_steam_eu",
    "GovHydro0": "dynamics.dynamics.turbine_governors.gov_hydro0",
    "GovGASTWD": "dynamics.dynamics.turbine_governors.gov_gastwd",
    "GovGAST2": "dynamics.dynamics.turbine_governors.gov_gast2",
    "PowerSystemStabilizer": "dynamics.dynamics.power_system_stabilizers.power_system_stabilizer",
    "PssIEEE4B": "dynamics.dynamics.power_system_stabilizers.pss_ieee4_b",
    "PssIEEE2B": "dynamics.dynamics.power_system_stabilizers.pss_ieee2_b",
    "PssSB4": "dynamics.dynamics.power_system_stabilizers.pss_sb4",
    "PssSB": "dynamics.dynamics.power_system_stabilizers.pss_sb",
    "PssSK": "dynamics.dynamics.power_system_stabilizers.pss_sk",
    "PssPTIST3": "dynamics.dynamics.power_system_stabilizers.pss_ptist3",
    "PssIEEE1A": "dynamics.dynamics.power_system_stabilizers.pss_ieee1_a",
    "PssIEEE3B": "dynamics.dynamics.power_system_stabilizers.pss_ieee3_b",
    "PssWSCC": "dynamics.dynamics.power_system_stabilizers.pss_wscc",
    "PssPTIST1": "dynamics.dynamics.power_system_stabilizers.pss_ptist1",
    "PssSH": "dynamics.dynamics.power_system_stabilizers.pss_sh",
    "GenSync": "dynamics.dynamics.generators.gen_sync",
    "GenLoad": "dynamics.dynamics.generators.gen_load",
    "GenAsync": "dynamics.dynamics.generators.gen_async",
    "GenEquiv": "dynamics.dynamics.generators.gen_equiv",
    "VcompIEEE": "dynamics.dynamics.voltage_compensator.vcomp_ieee",
    "VoltageCompensator": "dynamics.dynamics.voltage_compensator.voltage_compensator",
    "VcompCross": "dynamics.dynamics.voltage_compensator.vcomp_cross",
    "MotorAsync": "dynamics.dynamics.motors.motor_async",
    "MechanicalLoad": "dynamics.dynamics.motors.mechanical_load",
    "MechLoad1": "dynamics.dynamics.motors.mech_load1",
    "SynchronousMotorType": "dynamics.dynamics.motors.synchronous_motor_type",
    "MotorSync": "dynamics.dynamics.motors.motor_sync",
}

# EOF -------------------------------------------------------------------------
